### ISSUE TITLE
Implement proper pattern scanning with wildcards

### ISSUE THREAD

**Issue by fs-c** [fs-c/maniac#45]
1. ~~Support patterns like `FF ? ? 07 2A ? ? ? ? AC AB` and always return the address at the beginning of the pattern, ie. the address of FF in the above example. (This is required for #43 and #44.)~~
2. Support scanning for multiple patterns at once to avoid redunant reads. It's acceptable to assume that no two patterns overlap.
3. Support multiple patterns/desired value to future-proof some more.

**Comment by LW2904** [comment]
- When getting memory chunks to read make sure they overlap by `pattern_length - 1` to avoid missing patterns that span across two chunks.

**Comment by LW2904** [comment]
Updated issue to account for the refactor in `918bdd0`. 2. and 3. would still be nice but aren't particularly critical.
