### ISSUE TITLE
issue when using mirror/random mod

### ISSUE THREAD

**Issue by ANB1997** [fs-c/maniac#63]
when mirror/random mod is active, the app doesn't seem to be able to detect column order change. therefore it keeps playing the notes as if no mod is active. any way to solve this? like finding column order/active mod in memory

**Comment by LW2904** [comment]
Thanks for reporting this, didn't of think of that. I'll look into it.

**Comment by LW2904** [comment]
Okay so the random mod likely won't be supported in the hear future, no clue why it causes action parsing to fail that thoroughly. Mirror mod support seems simple enough, probably won't add in-memory detection (i.e. you'll have to supply a `--mirror` option or something).

**Comment by LW2904** [comment]
Took me a while to get to it but mirror mod is now supported.

```
    -m / --mirror-mod          Mirror the keys pressed (i.e.: mirror mod su
                               pport). (default: false, implicit: true)
```

I'm waiting on some other stuff before I make a new release but you can always download cutting edge builds by heading over to the [latest Action run](https://github.com/LW2904/maniac/actions/runs/164738118) (probably not the latest by the time anyone is reading this, but still) and downloading the "builds" artifact.
