### ISSUE TITLE
Auto Launch

### ISSUE THREAD

**Issue by chinrvaaaa** [fs-c/maniac#73]
Hi, when i open the osu mniac thing for the latest release, it says i have to disable auto launch. How do i do that?

**Comment by fs-c** [comment]
The message you are seeing almost certainly doesn't come from maniac itself. Can you post a screenshot?

**Comment by chinrvaaaa** [comment]
> The message you are seeing almost certainly doesn't come from maniac itself. Can you post a screenshot?

![image](https://user-images.githubusercontent.com/106627622/171279243-0bb76791-a422-4f3b-9260-738329a945a1.png)

**Comment by fs-c** [comment]
Huh, I have no clue where that message comes from. How are you starting maniac?

**Comment by chinrvaaaa** [comment]
> 

by running it as usual, by double clicking on it

**Comment by chinrvaaaa** [comment]
> Huh, I have no clue where that message comes from. How are you starting maniac?

but how do i disable auto launch though?

**Comment by fs-c** [comment]
I don't know what auto launch is supposed to be, this is not a message from maniac.

**Comment by chinrvaaaa** [comment]
> I don't know what auto launch is supposed to be, this is not a message from maniac. Edit: Out of curiosity, have you tried the debug build?

yes i have and im also missing files when i open it for some reason lol

**Comment by chinrvaaaa** [comment]
> I don't know what auto launch is supposed to be, this is not a message from maniac. Edit: Out of curiosity, have you tried the debug build?

ill try to reinstall windows and see if it works.
