### ISSUE TITLE
failed reading memory

### ISSUE THREAD

**Issue by chinrvaaaa** [fs-c/maniac#75]
how do i fix this error? 
![image](https://user-images.githubusercontent.com/106627622/205179999-ef56680e-7363-4445-b0c1-3f9603f3d84d.png)

**Comment by chinrvaaaa** [comment]
i still dont know how to fix the error lol but alright

**Comment by fs-c** [comment]
> i still dont know how to fix the error lol but alright

Should be fixed in v2.0.1, no?

**Comment by chinrvaaaa** [comment]
lol i think osu has patched hacks
