### ISSUE TITLE
memory v2.0.2 / 2.0.1

### ISSUE THREAD

**Issue by cheatengine69** [fs-c/maniac#77]
Hi, I'm having an issue with 
**status: failed reading memory** 

i've seen same issue marked as closed here: https://github.com/fs-c/maniac/issues/75#issue-1472091810
> Should be fixed in v2.0.1, no?

I've tried both; v2.0.1 and v2.0.2 and problem happens in both cases

osu: stable 20221208.5

![image](https://user-images.githubusercontent.com/120567121/207586013-2e801b1e-5bb3-4fcc-97d3-625b951d0fd0.png)

**Comment by fs-c** [comment]
It looks like there was an osu update shortly after I fixed a bug that caused the same error.

Will need to fix a signature.

**Comment by chinrvaaaa** [comment]
yeah its patched

**Comment by Delta658** [comment]
> yeah its patched

bro,how did you patch it
