### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mahuyre** [fs-c/maniac#83]
Whenever I open it and go into a beatmap it says found beatmap but won't change it to playing status, I tried to use the debug menu and when I went into a beatmap there were lot's of error messages saying it couldn't find the map

**Comment by SteezySaturn** [comment]
its broken

**Comment by mahuyre** [comment]
🤯🤯🤯🤯🤯🤯

**Comment by fs-c** [comment]
Duplicate of #82
