### ISSUE TITLE
Give the sliders some consistancy

### ISSUE THREAD

**Issue by Twiston-7** [fs-c/maniac#84]
The humanization slider only works in the box
The randomization works wherever on screen you drag your cursor, and can also take numbers as input if you double click
The compensation and tap time don't work with a slider, but with numbers and plusses (my preference personally since you can set specific numbers, which is hard to do with the randomization and impossible for certain numbers on the humanization, since the smallest increase/decrease is 3, but sometimes 4)

https://user-images.githubusercontent.com/97396676/230588891-c49cb717-33c0-4ae7-b86e-766cf08b0236.mp4

**Comment by fs-c** [comment]
You can set a specific value for a slider using Ctrl+LMB, see the probably too small and inconspicous note at the bottom of the window.

But in general I agree, all values should just be raw number inputs. I still prefer the slider for humanization in particular (it's a value that should be adjusted on a per-user basis to fit their requirements, moving it in small increments, not an exact value to be copied from another config) but the usability isn't obvious and it probably doesn't meet my goal anyways.

I'll change this in the next version.
