### ISSUE TITLE
Fix humanizer being off by a constant amount and always to the right

### ISSUE THREAD

**Issue by Twiston-7** [fs-c/maniac#85]
Whenever the humanizer is used (dynamic one), on fast parts, it will always be off by a constant amount and always to the right (top video), when in reality (keeping in mind I'm a really bad player), hits are kind of all over the place (second video), and third video includes a top player playing a hard map for some more reference

Settings for maniac in the top image
![Screenshot 2023-04-07 120654](https://user-images.githubusercontent.com/97396676/230590405-65cc1ce9-a072-4cec-96e7-a3716de6fe61.png)

Maniac playing:
https://user-images.githubusercontent.com/97396676/230590301-0d233fcd-9753-4a8a-ab05-c2b2a9acbed9.mp4

Me playing:
https://user-images.githubusercontent.com/97396676/230590443-cfcfb640-6a58-4a99-b48e-3dd2870adddb.mp4

Top player playing a hard map:
https://youtu.be/_f3nwY1rc90?t=60

**Comment by fs-c** [comment]
Thanks for the illustrative videos. This might be a bug with the new humanization, I'll look into it.
