### ISSUE TITLE
Maniac will never break combo, and no option to do so

### ISSUE THREAD

**Issue by Twiston-7** [fs-c/maniac#87]
Basically as the title suggests. Either you set the humanization/randomization very high and it will be all over the place and sometimes miss, or, if you want it to get decent scores, you set them both at a place where they will hit some 200s in fast parts, but there is no way the program will accidentally drop a note. Maybe a nice feature to add would be the option to have a chance to miss a note at high notes per second after the combo is x high

**Comment by fs-c** [comment]
As I understand the idea you're suggesting, it is a special case of #88 so I'll close it in favor of that.
